// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScyMB6GZ5aJo-3mpC_SiW5hHQLPy07Ps',
    appId: '1:421229550208:web:f24057bbee55e86697e465',
    messagingSenderId: '421229550208',
    projectId: 'todo-3ca08',
    authDomain: 'todo-3ca08.firebaseapp.com',
    storageBucket: 'todo-3ca08.firebasestorage.app',
    measurementId: 'G-XM2NBPKYES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXCGR6IE1CFXC5yrKUlmcBSsu9eHwl5T8',
    appId: '1:421229550208:android:df7cf6bae5490c5c97e465',
    messagingSenderId: '421229550208',
    projectId: 'todo-3ca08',
    storageBucket: 'todo-3ca08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYCkp9zDxXj9sqIgnnvlydgRSPfZcFv4Y',
    appId: '1:421229550208:ios:084e4c374994c83297e465',
    messagingSenderId: '421229550208',
    projectId: 'todo-3ca08',
    storageBucket: 'todo-3ca08.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYCkp9zDxXj9sqIgnnvlydgRSPfZcFv4Y',
    appId: '1:421229550208:ios:084e4c374994c83297e465',
    messagingSenderId: '421229550208',
    projectId: 'todo-3ca08',
    storageBucket: 'todo-3ca08.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAScyMB6GZ5aJo-3mpC_SiW5hHQLPy07Ps',
    appId: '1:421229550208:web:ba46884d97f8f71e97e465',
    messagingSenderId: '421229550208',
    projectId: 'todo-3ca08',
    authDomain: 'todo-3ca08.firebaseapp.com',
    storageBucket: 'todo-3ca08.firebasestorage.app',
    measurementId: 'G-2E62KY6TH2',
  );

}